import test from 'node:test';import assert from 'node:assert/strict';
import {validateLayoutDocument,collectLayoutSlots,layoutNodeCount,makeSplitLayout} from '../packages/runtime/layout.js';

const doc={format:'datapass.studio.layout',version:1,id:'analysis',title:'Analysis',root:{id:'root',kind:'split',axis:'horizontal',ratio:.32,resizable:true,first:{id:'catalog',kind:'slot',slot:'figures',label:'Figures'},second:{id:'work',kind:'tabs',defaultTab:'pdf',tabs:[{id:'pdf',label:'Document',child:{id:'pdf-slot',kind:'slot',slot:'document'}},{id:'data',label:'Data',child:{id:'data-slot',kind:'slot',slot:'data'}}]}}};
test('layout validates and returns deterministic slot discovery',()=>{assert.equal(validateLayoutDocument(doc),doc);assert.deepEqual(collectLayoutSlots(doc),['figures','document','data']);assert.equal(layoutNodeCount(doc),5);});
test('layout rejects duplicate placements and executable/unknown fields',()=>{const bad=structuredClone(doc);bad.root.second.tabs[1].child.slot='document';assert.throws(()=>validateLayoutDocument(bad),/Duplicate slot/);assert.throws(()=>validateLayoutDocument({...doc,onLoad:'run()'}),/Unknown/);});
test('known slot contract rejects an undeclared consumer surface',()=>{assert.throws(()=>validateLayoutDocument(doc,{knownSlots:['figures','document']}),/Unknown layout slot: data/);});
test('split helper remains inert and bounded',()=>{const value=makeSplitLayout('compare','Compare','baseline','candidate',{ratio:.5});assert.deepEqual(collectLayoutSlots(value),['baseline','candidate']);assert.equal(value.root.ratio,.5);assert.throws(()=>makeSplitLayout('bad','Bad','a','b',{ratio:1}));});
test('depth and node limits prevent pathological imported layouts',()=>{let child={id:'leaf',kind:'slot',slot:'leaf'};for(let i=0;i<13;i++)child={id:'stack'+i,kind:'stack',direction:'vertical',gap:0,children:[child]};const deep={format:'datapass.studio.layout',version:1,id:'deep',title:'Deep',root:child};assert.throws(()=>validateLayoutDocument(deep),/complex/);});
