import test from 'node:test';import assert from 'node:assert/strict';
import {ReactiveGraph} from '../packages/runtime/reactive.js';
import {TaskRegistry,TaskCoordinator} from '../packages/runtime/tasks.js';
import {SessionTrace} from '../packages/runtime/trace.js';
import {validateAppManifest,manifestFromClient} from '../packages/runtime/app-spec.js';
import {motionRig} from '../clients/motion-rig.js';

test('reactive graph recomputes only invalidated dependency chain',()=>{let sumRuns=0,doubleRuns=0;const g=new ReactiveGraph();g.defineSource('a',1).defineSource('b',2).defineComputed('sum',['a','b'],(a,b)=>(sumRuns++,a+b)).defineComputed('double',['sum'],sum=>(doubleRuns++,sum*2));assert.equal(g.get('double'),6);assert.deepEqual([sumRuns,doubleRuns],[1,1]);assert.equal(g.get('double'),6);assert.deepEqual([sumRuns,doubleRuns],[1,1]);g.set('a',4);assert.equal(g.get('double'),12);assert.deepEqual([sumRuns,doubleRuns],[2,2]);});
test('reactive transactions emit once and atomic patches validate first',()=>{const g=new ReactiveGraph();g.defineSource('x',1,{validate:v=>Number.isFinite(v)}).defineSource('y',2,{validate:v=>Number.isFinite(v)});let events=0;g.subscribe(()=>events++);g.patch({x:3,y:4});assert.equal(events,1);assert.deepEqual(g.snapshot(['x','y']).values,{x:3,y:4});assert.throws(()=>g.patch({x:5,y:NaN}));assert.deepEqual(g.snapshot(['x','y']).values,{x:3,y:4});});
test('reactive explanation exposes semantic dependency tree',()=>{const g=new ReactiveGraph();g.defineSource('parameter.x',2,{meta:{role:'input'}}).defineComputed('metric.area',['parameter.x'],x=>x*x,{meta:{role:'metric'}});assert.equal(g.explain('metric.area').deps[0].id,'parameter.x');});
test('task coordinator marks result stale when input revision moved',async()=>{const registry=new TaskRegistry().register('evaluate',async(input,{report})=>{report(.5,'half');return {value:input*2};});let revision=2;const q=new TaskCoordinator(registry);const out=await q.run('evaluate',4,{inputRevision:1,isRevisionCurrent:r=>r===revision});assert.equal(out.status,'stale');assert.equal(out.value,undefined);});
test('new task with same key cancels older task',async()=>{const registry=new TaskRegistry().register('work',(input,{signal})=>new Promise((resolve,reject)=>{const t=setTimeout(()=>resolve(input),20);signal.addEventListener('abort',()=>{clearTimeout(t);const e=new Error('aborted');e.name='AbortError';reject(e);},{once:true});}));const q=new TaskCoordinator(registry);const a=q.run('work',1,{key:'same'});await new Promise(r=>setTimeout(r,1));const b=q.run('work',2,{key:'same'});assert.equal((await a).status,'cancelled');assert.equal((await b).status,'ready');});
test('task history is bounded',async()=>{const registry=new TaskRegistry().register('x',async x=>x);const q=new TaskCoordinator(registry,{maxHistory:2});await q.run('x',1,{key:'a'});await q.run('x',2,{key:'b'});await q.run('x',3,{key:'c'});assert.equal(q.history().length,2);});
test('session trace is bounded and exports inert scalar metadata',()=>{const trace=new SessionTrace({maxEvents:2,clock:(()=>{let n=0;return()=>++n;})()});trace.record('selection','select',{entityId:'a'});trace.record('view','camera',{meta:{mode:'iso'}});trace.record('task','ready',{inputRevision:2});const out=trace.export({clientId:'motion-rig',clientVersion:'1.0.0'});assert.equal(out.events.length,2);assert.equal(out.events.at(-1).inputRevision,2);assert.throws(()=>trace.record('custom','bad',{meta:{payload:{secret:true}}}));});
test('app manifest validator rejects executable/unknown surface fields',()=>{const base={format:'datapass.studio.app',schemaVersion:1,id:'demo',title:'Demo',version:'1',description:'',classification:'synthetic',parameters:[],views:[{id:'lab',label:'Lab',kind:'lab',icon:'panel',description:''}],tasks:[],artifacts:[]};assert.equal(validateAppManifest(base),base);assert.throws(()=>validateAppManifest({...base,run:'eval(x)'}));});
test('trusted client can expose a serializable manifest without function leakage',()=>{const manifest=manifestFromClient(motionRig);const text=JSON.stringify(manifest);assert.equal(manifest.id,'motion-rig');assert.equal(typeof manifest.parameters[0].default,'number');assert.ok(!text.includes('function'));assert.ok(!('frame' in manifest));});
