import test from 'node:test';import assert from 'node:assert/strict';
import {motionRig} from '../clients/motion-rig.js';import {transferBench} from '../clients/transfer-bench.js';
import {WorkspaceStore,PlaybackStore} from '../packages/runtime/store.js';
import {boundedJson,canonical,validateClient,validateDocument,validateParameters,validateFrame,validateEvaluationResponse} from '../packages/runtime/validation.js';
import {SaveQueue} from '../packages/runtime/persistence.js';
import {RendererRegistry,LatestRequest} from '../packages/runtime/registry.js';
import {artifactCatalog,artifactsForEntity,artifactForSelection,documentForArtifact,safeDocumentTarget,validateArtifactCatalog} from '../packages/runtime/artifacts.js';
const store=()=>new WorkspaceStore(motionRig);
const result=req=>({...req,metrics:[{id:'x',label:'X',value:1,unit:'m',note:'synthetic'}]});

test('canonical JSON independent of key insertion order',()=>assert.equal(canonical({z:1,a:[3,2]}),canonical({a:[3,2],z:1})));
test('JSON rejects prototype and depth attacks',()=>{assert.throws(()=>boundedJson('{"__proto__":1}'));assert.throws(()=>boundedJson('['.repeat(30)+'1'+']'.repeat(30)));});
test('JSON byte limit includes multibyte characters',()=>assert.throws(()=>boundedJson('"'+String.fromCodePoint(233).repeat(10)+'"',15)));
test('both unrelated clients satisfy the same contract',()=>{assert.equal(validateClient(motionRig),motionRig);assert.equal(validateClient(transferBench),transferBench);});
test('client duplicate fields rejected',()=>assert.throws(()=>validateClient({...motionRig,parameters:[...motionRig.parameters,motionRig.parameters[0]]})));
test('unknown parameter, bool, NaN and out-of-bounds are rejected atomically',()=>{const s=store(),before=s.state.parameters;for(const [k,v]of [['extra',5],['span',true],['span',NaN],['span',Infinity],['span',100]])assert.equal(s.updateParameter(k,v),false);assert.equal(s.state.parameters,before);assert.equal(s.state.revision,0);});
test('dependency validation rejects impossible geometry',()=>{const c={...motionRig,parameters:motionRig.parameters.map(p=>p.id==='arm'?{...p,min:.01}:p)};assert.ok(validateParameters(c,{...c.defaults,arm:.1}).length);});
test('one parameter change creates an immutable next state and undo',()=>{const s=store(),old=s.state;assert.ok(s.updateParameter('span',7));assert.equal(old.parameters.span,6);assert.equal(s.state.revision,1);assert.equal(s.state.history.undo,1);assert.ok(Object.isFrozen(s.state.parameters));});
test('one drag is one undo transaction',()=>{const s=store();s.beginEdit();for(const v of [6.2,6.8,7.2])s.updateParameter('span',v,{grouped:true});s.endEdit();assert.equal(s.state.history.undo,1);s.undo();assert.equal(s.state.parameters.span,6);s.redo();assert.equal(s.state.parameters.span,7.2);});
test('cancel edit restores values without new undo entry',()=>{const s=store();s.beginEdit();s.updateParameter('span',8,{grouped:true});s.cancelEdit();assert.equal(s.state.parameters.span,6);assert.equal(s.state.history.undo,0);});
test('new edit invalidates redo',()=>{const s=store();s.updateParameter('span',7);s.undo();s.updateParameter('span',8);assert.equal(s.state.history.redo,0);});
test('bounded history retains only 64 snapshots',()=>{const s=store();for(let i=0;i<100;i++)s.updateParameter('span',6+i/100);assert.equal(s.state.history.undo,64);});
test('scenario reference remains immutable and undo restores matching baseline',()=>{const s=store();s.setScenario('compact');s.updateParameter('span',4);s.undo();s.undo();assert.equal(s.state.scenarioId,'standard');assert.equal(s.baseline.span,6);s.reset();assert.equal(s.state.parameters.span,6);});
test('selection and hidden ids are validated',()=>{const s=store();assert.equal(s.select('absent'),false);assert.equal(s.select('panel-a'),true);s.toggleHidden('panel-a');assert.deepEqual(s.state.hidden,['panel-a']);s.showAll();assert.deepEqual(s.state.hidden,[]);});
test('presentation changes do not create scientific input revisions',()=>{const s=store();s.setView({yaw:30});s.select('panel-a');assert.equal(s.state.revision,0);assert.ok(s.state.dirty);});
test('save success really clears dirty state',()=>{const s=store();s.updateParameter('span',7);s.setSaveStatus('saved',true);assert.equal(s.state.dirty,false);});
test('document export/import roundtrip without mutating reference',()=>{const s=store();s.updateParameter('span',7);s.setView({mode:'plans',yaw:32});s.select('panel-a');const d=s.document(),t=store();validateDocument(motionRig,d);t.importDocument(d);assert.equal(t.state.parameters.span,7);assert.equal(t.baseline.span,6);assert.equal(t.state.view.mode,'plans');assert.equal(t.state.selection,'panel-a');});
test('restore preserves revision and is clean',()=>{const s=store();s.updateParameter('span',7);const t=store();t.restore(s.document());assert.equal(t.state.revision,s.state.revision);assert.equal(t.state.dirty,false);});
for(const [name,change]of [
 ['wrong client',d=>d.clientId='transfer-bench'],['unknown version',d=>d.version=8],['unknown field',d=>d.injected=true],
 ['invalid camera',d=>d.view.camera='eval'],['non-finite pose',d=>d.view.yaw=NaN],['unknown hidden part',d=>d.hidden=['missing']],
 ['duplicate hidden part',d=>d.hidden=['panel-a','panel-a']],['promoted provenance',d=>d.provenance.reviewed=true],['private/public promotion',d=>d.provenance.classification='private']])
 test('document refuses '+name,()=>{const s=store(),doc=s.document();change(doc);assert.throws(()=>s.importDocument(doc));assert.equal(s.state.revision,0);});
test('stale evaluation cannot replace current parameters',()=>{const s=store(),req=s.requestEvaluation();s.updateParameter('span',8);assert.equal(s.acceptEvaluation(result(req),req),false);assert.equal(s.state.evaluation,null);assert.equal(s.state.evaluationStatus,'stale');});
test('response correlation and numeric output validated',()=>{const s=store(),req=s.requestEvaluation();assert.throws(()=>s.acceptEvaluation({...result(req),requestId:'other'},req));assert.throws(()=>validateEvaluationResponse({...result(req),metrics:[{id:'m',label:'bad',value:NaN,unit:'',note:''}]}));});
test('newer request wins even with equal parameters and revision',()=>{const s=store(),a=s.requestEvaluation(),b=s.requestEvaluation();assert.equal(s.acceptEvaluation(result(a),a),false);assert.equal(s.acceptEvaluation(result(b),b),true);assert.equal(s.state.evaluation.requestId,b.requestId);});
test('valid response becomes stale on an edit',()=>{const s=store(),req=s.requestEvaluation();assert.ok(s.acceptEvaluation(result(req),req));s.updateParameter('span',8);assert.equal(s.state.evaluationStatus,'stale');});
test('playback is independent of document and history',()=>{const s=store(),doc=canonical(s.document()),p=new PlaybackStore({raf:()=>1,cancel:()=>{}});for(let i=0;i<100;i++)p.set({phase:i/100});assert.equal(canonical(s.document()),doc);assert.equal(s.state.history.undo,0);p.dispose();});
test('reduced motion prevents autoplay but allows manual stepping',()=>{const p=new PlaybackStore({raf:()=>1,cancel:()=>{}});p.set({reducedMotion:true,playing:true});assert.equal(p.state.playing,false);p.set({phase:.8});assert.equal(p.state.phase,.8);p.set({playing:true});assert.equal(p.state.playing,false);p.dispose();});
test('frame loop has bounded delta and releases its scheduled task',()=>{let cb,cancelled=0;const p=new PlaybackStore({raf:f=>(cb=f,1),cancel:()=>cancelled++});p.set({phase:0,period:1,playing:true});cb(0);cb(2000);assert.ok(p.state.phase<=.100001);p.dispose();assert.ok(cancelled>0);});
test('late save completion never announces newer data saved',async()=>{const statuses=[],calls=[],resolvers=[];const q=new SaveQueue(async d=>{calls.push(d);await new Promise(r=>resolvers.push(r));},s=>statuses.push(s));q.enqueue(1);await new Promise(r=>setImmediate(r));q.enqueue(2);resolvers.shift()();await new Promise(r=>setImmediate(r));assert.ok(!statuses.includes('saved'));resolvers.shift()();await q.chain;assert.deepEqual(calls,[1,2]);assert.equal(statuses.at(-1),'saved');});
test('save failures remain visible and retry can succeed',async()=>{let fail=true;const states=[],q=new SaveQueue(async()=>{if(fail)throw Error('quota');},s=>states.push(s));await q.enqueue({});assert.equal(states.at(-1),'error');fail=false;await q.enqueue({});assert.equal(states.at(-1),'saved');});
test('renderer registration and missing adapter errors are explicit',()=>{const r=new RendererRegistry().register({id:'a',mount:()=>{}});assert.equal(r.get('a').id,'a');assert.throws(()=>r.get('missing'));assert.throws(()=>r.register({id:'a',mount:()=>{}}));});
test('latest-request coordinator rejects reordered completions',async()=>{const q=new LatestRequest();let finish;const old=q.run(()=>new Promise(r=>finish=r));const newer=await q.run(async()=>2);finish(1);assert.ok(newer.current);assert.equal((await old).current,false);q.cancel();});
test('scene validation rejects broken transforms and repeated ids',()=>{const f=motionRig.frame(motionRig.defaults,.2,{yaw:0,explode:0});validateFrame(f);assert.throws(()=>validateFrame({...f,parts:[f.parts[0],f.parts[0]]}));assert.throws(()=>validateFrame({...f,parts:[{...f.parts[0],matrix:Array(16).fill(NaN)}]}));});

test('older rejected request cannot overwrite a newer successful result',async()=>{const q=new LatestRequest();let fail;const a=q.run(()=>new Promise((resolve,reject)=>fail=reject));await q.run(async()=>2);fail(new Error('late old failure'));assert.equal((await a).current,false);});
test('presentation mutation refuses unknown keys and nonboolean flags',()=>{const s=store();s.setView({script:'bad'});s.setView({edges:'true'});assert.equal(s.state.view.script,undefined);assert.equal(s.state.view.edges,true);assert.equal(s.state.dirty,false);});


test('artifact catalogs on unrelated clients validate as inert data',()=>{for(const client of [motionRig,transferBench]){const cat=artifactCatalog(client);assert.ok(cat.artifacts.length>0);assert.ok(cat.documents.length>0);validateArtifactCatalog(cat,new Set(client.frame(client.defaults,0,{yaw:0,explode:0,scenarioId:client.scenarios?.[0]?.id}).parts.map(p=>p.id)));}});
test('artifact selection follows stable scene identity without domain knowledge',()=>{const cat=artifactCatalog(motionRig),linked=artifactsForEntity(cat,'panel-a');assert.ok(linked.some(a=>a.id==='motion-profile'));assert.equal(artifactForSelection(cat,'panel-a'),'motion-profile');assert.equal(documentForArtifact(cat,linked[0]).id,'motion-note');});
test('artifact contract rejects external URLs and dangling scene identities',()=>{const external={documents:[{id:'doc-x',title:'X',mime:'application/pdf',sourceKind:'synthetic',url:'https://example.com/a.pdf'}],artifacts:[]};assert.throws(()=>validateArtifactCatalog(external));const bad={...motionRig,artifactCatalog:{...motionRig.artifactCatalog,artifacts:[{...motionRig.artifactCatalog.artifacts[0],entityIds:['missing-part']}]}};assert.throws(()=>validateClient(bad));});
test('local PDF target is page-addressable without executable URL schemes',()=>{assert.equal(safeDocumentTarget({url:'./public/private-client/reference.pdf',mime:'application/pdf'},7),'./public/private-client/reference.pdf#page=7');assert.throws(()=>safeDocumentTarget({url:'javascript:alert(1)',mime:'application/pdf'},1));});
test('reference workspace mode survives guarded document roundtrip',()=>{const s=store();s.setView({mode:'references'});const doc=s.document();validateDocument(motionRig,doc);const t=store();t.importDocument(doc);assert.equal(t.state.view.mode,'references');});
